import pandas as pd
from fpdf import FPDF
import datetime

def generate_pdf_report(df: pd.DataFrame, title: str = "VianaChat Analytics Report"):
    """
    Generates a professional PDF report from a DataFrame.
    Includes dynamic column sizing, branding, and character sanitization.
    """
    class PDF(FPDF):
        def header(self):
            # Logo placeholder or Brand Name
            self.set_font('Arial', 'B', 15)
            self.set_text_color(0, 86, 210) # Viana Blue
            self.cell(0, 10, 'VIANA', ln=True, align='L')
            self.set_draw_color(0, 86, 210)
            self.line(10, 20, 200, 20)
            self.ln(5)

        def footer(self):
            self.set_y(-15)
            self.set_font('Arial', 'I', 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, f'Page {self.page_no()} | Generated by VianaChat', 0, 0, 'C')

    pdf = PDF()
    pdf.add_page()
    
    # Report Title and Metadata
    pdf.set_font("Arial", 'B', 16)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, title, ln=True, align='L')
    
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 5, f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.cell(0, 5, f"Total Records Found: {len(df)}", ln=True)
    pdf.ln(10)
    
    if df.empty:
        pdf.set_font("Arial", 'I', 12)
        pdf.cell(0, 10, "No data available for this report.", ln=True)
        return bytes(pdf.output(dest='S'))

    # --- TABLE LOGIC ---
    cols = df.columns.tolist()
    # Dynamic Column Width Calculation (Basic)
    # We allocate 95% of the width (epw) across columns
    effective_width = pdf.epw
    col_width = effective_width / len(cols) if len(cols) > 0 else effective_width
    
    # Table Header
    pdf.set_font("Arial", 'B', 9)
    pdf.set_fill_color(0, 86, 210) # Viana Blue
    pdf.set_text_color(255, 255, 255)
    
    for col in cols:
        header_text = str(col).upper()
        # Truncate if too long for the cell
        if len(header_text) > 15: header_text = header_text[:12] + "..."
        pdf.cell(col_width, 10, header_text, border=1, fill=True, align='C')
    pdf.ln()
    
    # Table Rows
    pdf.set_font("Arial", '', 8)
    pdf.set_text_color(0, 0, 0)
    
    # Iterate through data (limit to 100 for PDF stability)
    for i, (_, row) in enumerate(df.head(100).iterrows()):
        # Zebra striping for readability
        fill = i % 2 == 0
        if fill:
            pdf.set_fill_color(245, 247, 250)
        else:
            pdf.set_fill_color(255, 255, 255)
            
        for col in cols:
            val = str(row[col])
            # Handle Encoding and Length
            if len(val) > 25: val = val[:22] + "..."
            
            # Clean non-latin-1 characters to avoid FPDF errors
            try:
                val.encode('latin-1')
            except UnicodeEncodeError:
                val = val.encode('ascii', 'ignore').decode('ascii')
                
            pdf.cell(col_width, 8, val, border=1, fill=True)
        pdf.ln()
        
    if len(df) > 100:
        pdf.ln(5)
        pdf.set_font("Arial", 'I', 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 10, f"* Report truncated to first 100 rows (Total: {len(df)})", ln=True)

    # Return as explicitly cast bytes to fix 'Invalid binary data format' error
    # fpdf2's dest='S' returns a bytearray, Streamlit needs bytes
    return bytes(pdf.output(dest='S'))